### PR TITLE
Added Python Program to do google search

### PR DESCRIPTION
**Pull request by abhishekmishragithub**

### CODE REVIEW

**Comment by ajmalsiddiqui** [comment]
As you can see in the log of the CI script, the name in `scripts/README.md` should be the same as the name of the directory with the script. Your directory name is "googleSearch" but the README file says "Google Search". Please fix this and make a commit. We will review your script after the CI passes.

**Comment by abhishekmishragithub** [comment]
ok, i'll do chnages

**Comment by itsron717** [comment]
I checked the script and it looks like you've just hardcoded the query `selenium` in the script. Generalize the script so that it works for any query and if possible take the query as a command line argument, example - `python main.py football` so that it's easier for people to use. For this you can use the following [link](https://www.pythonforbeginners.com/argparse/argparse-tutorial) as a source to learn and also try out new features for the script. After those changes are done (and also the Build passes) we can review it. :)

**Review by itsron143 — COMMENTED** [review]
You also got to change the name to `googleSearch` in `scripts/README.md`.

**Review by itsron143 — COMMENTED** [review]
`google_search` would be a better name as it follows the conventions.

**Comment by icyphox** [comment]
@abhishekmishragithub it's probably easier (and cleaner) to do this with a HTTP focused library; think [requests](https://github.com/requests/requests).

**Comment by abhishekmishragithub** [comment]
@icyphox same task can we achieve with HTTP focused library , but i was exploring selenium hence wrote this script. Since the repo mentioned you can add your simple scripts as well hence i added this dumb scipt.
Don't worry i'll write good script as well and uploading soon.

**Comment by itsron717** [comment]
`selenium` is still hardcoded in the script. Generalize it and look at the previous comments for other possible features that can be added to this.

**Comment by 1cedsoda** [comment]
@abhishekmishragithub Can you squash the commits?

**Pull request closed without merging**
