### PR TITLE
Adding basic tests for repo integrity and a CI server

### PR DESCRIPTION
**Pull request by ajmalsiddiqui**
The aim is to have a few scripts to run tests to ensure that the repository content is exactly how we want it to be. Also, to add a CI server to the repo that can run these tests whenever a PR is generated/a push or merge is made and implement status checks and a README badge using the CI service.

To-Do:
- [x] Develop the scripts for testing
- [x] Setup CI for repo and commit its config file(s)
- [x] Update CONTRIBUTIONS.md and appropriate README files to reflect our standards for PRs
- [x] Resolve any inconsistencies that currently exist with the repo so that the tests don't fail due to content added before CI is integrated

### CODE REVIEW

**Comment by ajmalsiddiqui** [comment]
Currently only one test script exists that ensures that all the directories in the `scripts` folder have corresponding entries in the `scripts/README.md` file. I've marked the "add test scripts" item as complete for now. Additional tests can be added as needed later.

**Comment by ajmalsiddiqui** [comment]
@itsron717 this should be enough to set up basic CI in the repo. Review everything and squash the commits before merging. :)

**Comment by itsron717** [comment]
The template format in scripts/readme got unstructured now.

**Comment by ajmalsiddiqui** [comment]
Fixed it :)

**Pull request merged**
